### ISSUE TITLE
页面刷新后分页失效  page loading fail before f5

### ISSUE THREAD

**Issue by wannvmi** [zhhlwd/vuepress-theme-indigo-material#13]

**Comment by zhhlwd** [comment]
因为其实打开首页时全部分页的数据已经在本地构建时生成好了，点击页数只是截取展示对应页的数据，并没有真正的去发请求，URL也没有变化，如果要刷新保存当前页数，我可以尝试改变URL，然后在页面初始化时读取URL的页数参数，展示对应页数。
不过点击分页后又刷新这种情况应该比较少见，我不确定是否值得去兼容这种情况。

**Comment by wannvmi** [comment]
你点开 这一页试试 
https://zhhlwd.gitee.io/posts/javascript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B9%8B%E8%AE%BE%E8%AE%A1%E5%8E%9F%E5%88%99.html
点击上一篇下一篇都失效了 history url 改变了

**Comment by zhhlwd** [comment]
控制台报错app.4412ed54.js:7 DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
[nuxt.js issue](https://github.com/nuxt/nuxt.js/issues/1552)
一般都是ssr引起的，预测是因为预渲染时，评论插件Vssue并没有完全渲染到html中，然后只要在文章页刷新时vue插入节点就会报错，还会导致页面功能完全错乱。
我正在想办法解决，一个暂时的办法是把Vssue关掉，在docs/.vuepress/config.js的vssue字段，如果需要评论功能,需要把它的 need 改为 true, 不需要就改为 false

**Comment by zhhlwd** [comment]
> 你点开 这一页试试
> https://zhhlwd.gitee.io/posts/javascript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B9%8B%E8%AE%BE%E8%AE%A1%E5%8E%9F%E5%88%99.html
> 点击上一篇下一篇都失效了 history url 改变了

已经修复，请下载1.0.15，不过分页的问题不打算兼容，因为这种情况其实很少见，我自己用了主题这么久也没有遇到分页了再去刷新或误触刷新的情况，没必要再去增加代码的复杂度。

**Comment by wannvmi** [comment]
谢谢 啊 现在更新试试
