### ISSUE TITLE
请问是不是不支持表格

### ISSUE THREAD

**Issue by bajins** [zhhlwd/vuepress-theme-indigo-material#14]
md文件中有表格，但是编译后却没有表格样式

**Comment by zhhlwd** [comment]
是支持的，问题在于vuepress生成的类名变了，所以css样式就没选中，已经修复请下载1.0.16

**Comment by bajins** [comment]
> 是支持的，问题在于vuepress生成的类名变了，所以css样式就没选中，已经修复请下载1.0.16

好的，谢谢
