### ISSUE TITLE
生成的静态文件在哪里呢？

### ISSUE THREAD

**Issue by qingfengfenga** [zhhlwd/vuepress-theme-indigo-material#15]
生成的静态文件默认路径改变了吗？
[root@zabbix-test-01 wt-docs]# cnpm run build

> template@1.0.0 build /home/wt-docs
> vuepress build docs

**Comment by zhhlwd** [comment]
配置选项在[config.js](https://github.com/zhhlwd/vuepress-theme-indigo-material/blob/9d85b76909041758f8694caf8f295c14e52cfc9d/docs/.vuepress/config.js#L3)中

**Comment by qingfengfenga** [comment]
好的，找到了，非常感谢。我还有一个问题，
![QQ截图20190628175335](https://user-images.githubusercontent.com/41416092/60334370-f2102300-99cd-11e9-93ff-f850dfe3eead.png)
官方文档的这个位置，后面的标签是怎么设置的，网上找不到关于他的信息，是需要插件支持吗？

**Comment by zhhlwd** [comment]
你去看他github仓库里的docs源文件不就知道了吗，他用的是[自定义的组件](https://v1.vuepress.vuejs.org/zh/guide/using-vue.html)

**Comment by qingfengfenga** [comment]
找到了，再次感谢！
