### ISSUE TITLE
缺文件报错

### ISSUE THREAD

**Issue by ColinCLL** [zhhlwd/vuepress-theme-indigo-material#16]
https://github.com/zhhlwd/vuepress-theme-indigo-material/blob/master/enhanceApp.js#L1-L9

这里面的文件哪里来的？项目没这个目录，package.json里面也没

**Comment by zhhlwd** [comment]
https://github.com/zhhlwd/vuepress-theme-indigo-material/blob/dc0bb1b8f849c61fbd467bbaecc8166f3249f034/index.js#L30-L36

**Comment by ColinCLL** [comment]
谢谢了，是我没正确使用你的模板~~
