### ISSUE TITLE
手機平台,側邊欄打開後無法關閉的問題

### ISSUE THREAD

**Issue by thonyl19** [zhhlwd/vuepress-theme-indigo-material#18]
hi,博主你好:
在學習vuepress 時發現了你開發的主題,做得很棒,不過無意見發現了一個小問題,就是在手機的瀏覽頁面上,發現如果展開側邊欄位,頁面不會像在電腦的呈現上,有個關閉側欄的打X 圖示,結果就造成側欄打開後關不掉的情形.
因為,我目前vuepress 處於還在摸索階段 ,只能提供你我發現的狀況,還沒辦法協助fix 這個問題,所以只能通知你了,以上.

**Comment by zhhlwd** [comment]
在手机端打开，点开侧边栏，想把它关闭，只要点击侧边栏之外的灰色区域就行了。

**Comment by thonyl19** [comment]
OK,看來是我疏忽了, 謝謝回覆
