### ISSUE TITLE
最后更新时间的展示问题和默认标题大写问题

### ISSUE THREAD

**Issue by BuptStEve** [zhhlwd/vuepress-theme-indigo-material#3]
试用了下这个主题感觉不错~但还有些小疑问...

**问题**
比如，当前是凌晨 00:22 分更新的文章。会展示成 `最后更新时间：2019/2/22 上午12:22:52`

这个时间展示很容易让人误会是中午12点...

**方案**
采用 24 小时制怎么样？

**问题**
发现标题中的英文首字母都【被】大写了

**方案**
能不能不进行首字母大写操作？

**Comment by zhhlwd** [comment]
时间问题，我未能复现，请问你用的是哪个时间 ？时间匹配的顺序是md 文件顶部的信息中的 date 字段==>git 仓库的提交时间===>都没有那就是当前时间moment().format('YYYY-MM-DD HH:mm:ss')
至于标题，是vuepress默认转换的标题，你可以在这里找到配置方法[markdown.slugify](https://vuepress.vuejs.org/zh/config/#markdown-slugify)

**Comment by BuptStEve** [comment]
更新时间应该是 `vuepress/plugin-last-updated` 的锅。

[return new Date(timestamp).toLocaleString(lang)](https://github.com/vuejs/vuepress/blob/master/packages/@vuepress/plugin-last-updated/index.js#L18)

[使用 transformer 即可自定义](https://vuepress.vuejs.org/zh/plugin/official/plugin-last-updated.html#%E9%80%89%E9%A1%B9) 我回头试试...

首字母大写的原因是这个 https://github.com/zhhlwd/vuepress-theme-indigo-material/blob/bebc3f2c932ee44e2d2a51380a1e364bff3a6ee1/styles/content.styl#L21

**Comment by BuptStEve** [comment]
ps 可以提个 pr 给 https://github.com/ulivz/awesome-vuepress

![image](https://user-images.githubusercontent.com/11501493/53236679-d6b7a300-36cf-11e9-9e59-012e84d2e602.png)

**Comment by zhhlwd** [comment]
vuepress/plugin-last-updated的时间问题我会在内部尝试使用 transformer 自定义一下， 然后在今晚凌晨测试一下

**Comment by BuptStEve** [comment]
最后更新时间显示问题解决了，[按官方文档来搞就行](https://v1.vuepress.vuejs.org/zh/plugin/official/plugin-last-updated.html#%E9%80%89%E9%A1%B9)

```js
// .vuepress/config.js
module.exports = {
    plugins: [
        [
            '@vuepress/last-updated',
            {
                transformer: (timestamp) => {
                    const moment = require('moment')
                    return moment(timestamp).format('YYYY-MM-DD HH:mm:ss')
                },
            },
        ],
    ],
}
```

首字母大写那个要不然你把它删了？还是使用者自己在 `.vuepress/styles/index.styl` 里写样式？

```styl
.content {
    h1, h2, h3, h4, h5, h6 {
        text-transform none
    }
}
```

**Comment by zhhlwd** [comment]
已更新版本为1.0.3，请下载体验，首字母问题还是让用户自定义吧

**Comment by zhhlwd** [comment]
刚好完善了代码高亮，就顺便把标题的text-transform设为none了，可以下载1.0.4版本体验
