### ISSUE TITLE
摘要里含有html标签

### ISSUE THREAD

**Issue by elliottzheng** [zhhlwd/vuepress-theme-indigo-material#6]
![default](https://user-images.githubusercontent.com/22427645/53957295-f2339c80-4118-11e9-9add-98bbb6824c6b.png)
![default](https://user-images.githubusercontent.com/22427645/53957325-08415d00-4119-11e9-8338-e913d5c12035.png)
老哥你这个“摘要~~~”有点辣眼睛，然后采集出来的摘要还有html标签和markdown标记，这可不太行。下面是我的文章的源码。
```markdown
---
title: CopyTranslator
date: 2018-05-19 13:47:00
tags: [Python,CopyTranslator]
categories: [分享]
---

Foreign language assisted reading and translation solution
<!-- more -->
```

**Comment by zhhlwd** [comment]
优化了下摘要，请下载1.0.10
