### ISSUE TITLE
点击标签后所有的标题都变成了标签值

### ISSUE THREAD

**Issue by Cindy0401** [zhhlwd/vuepress-theme-indigo-material#8]
点击 <面试> 标签后，所有标题位置都变成了标签值，如下图
<img width="1109" alt="sample1" src="https://user-images.githubusercontent.com/30232600/57759200-07860200-772c-11e9-8475-cf9c56d8d1fa.png">
<img width="1311" alt="sample2" src="https://user-images.githubusercontent.com/30232600/57759217-0fde3d00-772c-11e9-85c5-e14794f758de.png">

**Comment by zhhlwd** [comment]
我这里没有复现这个情况，您刷新后是否一直是这样？

**Comment by Cindy0401** [comment]
刷新后标题正常，但是再次点击标签后问题又会复现

**Comment by zhhlwd** [comment]
说一下步骤还有浏览器环境，我看能不能复现

**Comment by Cindy0401** [comment]
浏览器：chrome

**Comment by Cindy0401** [comment]
浏览器：Chrome
步骤： 点击侧边栏<标签分类> -> 点击任意标签-> 点击侧边栏<主页>-> 点击任意文章

**Comment by zhhlwd** [comment]
我在Chrome没测出来，在Firefox复现了，已经修复，暂时部署上线测试了，可以点击我的博客测试看看还有没有：https://zhhlwd.gitee.io/              ，           https://zhhlwd.github.io/

**Comment by Cindy0401** [comment]
可以了👍
